version: 2
updates:

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    python-dependencies:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    action-dependencies:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"

- package-ecosystem: "gomod"
  directory: "/clients/go-tuf/"
  schedule:
    interval: "weekly"
