name: "tuf-conformance"
description: "TUF client conformance test suite"

inputs:
  entrypoint:
    description: "client-under-test CLI to invoke"
    required: true
  artifact-name:
    description: "Name to use for GitHub artifact upload. The 'entrypoint' will be used by default
      but if you call this action in a job matrix, make sure each call gets a unique name"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: "3.11"

    - name: Install test
      run: |
        echo "::group::Install test suite and dependencies"
        sudo apt install faketime
        pip install -e "${{ github.action_path }}"
        echo "::endgroup::"
      shell: bash

    - name: Run test suite
      id: tuf-conformance
      env:
        ENTRYPOINT: ${{ inputs.entrypoint }}
        TEST_LOCATION: ${{ github.action_path }}/tuf_conformance
        NAME: ${{ inputs.artifact-name }}
      run: |
        # create a sanitized name for the artifact upload
        if [[ -z $NAME ]]; then
          echo "NAME=test repositories for ${ENTRYPOINT##*/}" >> "$GITHUB_OUTPUT"
        else
          echo "NAME=$NAME" >> "$GITHUB_OUTPUT"
        fi

        # run test suite
        pytest -v "$TEST_LOCATION" \
          --entrypoint "$ENTRYPOINT" \
          --repository-dump-dir ./test-repositories \
      shell: bash

    - name: Upload repository dump
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{ steps.tuf-conformance.outputs.NAME }}
        path: test-repositories
