name: Publish client conformance report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch-results:
    name: Fetch ${{ matrix.name }} results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't stop if one client results download fails
      matrix:
        include:
          - name: python-tuf
            repo: theupdateframework/python-tuf
            workflow: conformance.yml
            branch: develop
          - name: tuf-js
            repo: theupdateframework/tuf-js
            workflow: conformance.yml
            branch: main
          - name: sigstore-java
            repo: sigstore/sigstore-java
            workflow: tuf-conformance.yml
            branch: main
          - name: sigstore-ruby
            repo: sigstore/sigstore-ruby
            workflow: ci.yml
            branch: main


    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@8305c0f1062bb0d184d09ef4493ecb9288447732 # v20
        with:
          # A token is required to read other repos' artifacts. This token is a fine grained token
          # with read-only "public repositories" access only. It is set to expire in 1 year
          # (maximum accepted by OpenSSF)
          github_token: ${{ secrets.READ_ONLY_TOKEN }}
          repo: ${{ matrix.repo }}
          workflow: ${{ matrix.workflow }}
          branch: ${{ matrix.branch }}
          name: tuf-conformance-results
          workflow_conclusion: completed
          path: ./results/
        continue-on-error: true

      - name: Rename artifact for aggregation
        run: |
          if [ -f "./results/tuf-conformance-report.json" ]; then
            mv ./results/tuf-conformance-report.json "./results/${{ matrix.name }}.json"
          else
            # create empty file so report generator can still include the client as "not found"
            mkdir ./results
            echo "{}" > "./results/${{ matrix.name }}.json"
          fi

      - name: Upload ${{ matrix.name }} results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ matrix.name }}-result
          path: ./results/${{ matrix.name }}.json

  build-report:
    name: Build client conformance report
    runs-on: ubuntu-latest
    needs: [fetch-results]
    if: always()

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download all individual results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: '*-result'
          path: ./results

      - name: Generate report
        run: |
          python .github/scripts/generate_client_report.py \
            --reports-dir ./results \
            --output results/index.html

      - name: Upload report for Pages
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: results/

  deploy-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-report
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
